[platformio]
build_dir = C:/tmp/pio_build/pn532_spi_probe

[env:xiao_esp32c6]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = seeed_xiao_esp32c6
framework = arduino
monitor_speed = 115200
lib_deps = adafruit/Adafruit PN532@^1.3.4
