[env:xiao_esp32s3]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
lib_deps = bblanchon/ArduinoJson@^7.4.1
build_flags = -I ../../shared
monitor_filters = esp32_exception_decoder
