'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),os=require('os'),path=require('path');
const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'wardrobe-tenants-'));
process.env.DATA_PATH=path.join(tmp,'db.json');process.env.PORT='0';process.env.DEVICE_TOKEN='tenant-device';process.env.JWT_SECRET='tenant-secret';process.env.SIMULATION_ENABLED='false';
const {server}=require('../backend/server');let origin;
const call=async(pathname,options={})=>{const r=await fetch(origin+pathname,{...options,headers:{'content-type':'application/json',...options.headers}});return{status:r.status,body:await r.json()}};
const auth=token=>({authorization:`Bearer ${token}`});
test.before(async()=>{await new Promise(ok=>server.listen(0,'127.0.0.1',ok));origin=`http://127.0.0.1:${server.address().port}`});
test.after(()=>server.close());
test('users only receive their own garments, rods and hangers',async()=>{
  const a=await call('/api/auth/signup',{method:'POST',body:JSON.stringify({name:'A',email:'a@example.com',password:'password-123'})});assert.equal(a.status,201);
  const shirt=await call('/api/garments',{method:'POST',headers:auth(a.body.token),body:JSON.stringify({name:'A의 셔츠',tagUid:'04112233445566'})});assert.equal(shirt.status,201);
  const device=await call('/api/gateway/status',{method:'POST',headers:{authorization:'Bearer tenant-device'},body:JSON.stringify({gatewayId:'GW-AABBCC',hangerId:'HC-AABBCC',state:'PRESENT',tagUid:'04112233445566',sequence:1,bootId:'a'})});assert.equal(device.status,200);
  const b=await call('/api/auth/signup',{method:'POST',body:JSON.stringify({name:'B',email:'b@example.com',password:'password-123'})});assert.equal(b.status,201);
  const bShirt=await call('/api/garments',{method:'POST',headers:auth(b.body.token),body:JSON.stringify({name:'B의 셔츠',tagUid:'04112233445566'})});assert.equal(bShirt.status,201,'different wardrobes may use the same NFC UID');
  const aSnap=await call('/api/snapshot',{headers:auth(a.body.token)}),bSnap=await call('/api/snapshot',{headers:auth(b.body.token)});
  assert.deepEqual(aSnap.body.garments.map(g=>g.name),['A의 셔츠']);assert.equal(aSnap.body.gateways.length,1);assert.equal(aSnap.body.hangers.length,1);
  assert.deepEqual(bSnap.body.garments.map(g=>g.name),['B의 셔츠']);assert.equal(bSnap.body.gateways.length,0);assert.equal(bSnap.body.hangers.length,0);
  const forbidden=await call(`/api/garments/${shirt.body.id}`,{method:'DELETE',headers:auth(b.body.token)});assert.equal(forbidden.status,404);
  const command=await call('/api/commands',{method:'POST',headers:auth(b.body.token),body:JSON.stringify({targets:['HC-AABBCC']})});assert.equal(command.status,404);
});
