#pragma once
#define WIFI_SSID "YOUR_2_4_GHZ_WIFI"
#define WIFI_PASSWORD "YOUR_WIFI_PASSWORD"
#define CLOUD_BASE_URL "http://192.168.0.100:8787"
#define DEVICE_TOKEN "SAME_VALUE_AS_SERVER_ENV"
#define ALLOW_INSECURE_HTTP 1
