#pragma once
#define NFC_SCAN_INTERVAL_MS 220
#define NFC_PRESENT_CONFIRM_COUNT 3
#define NFC_EMPTY_CONFIRM_COUNT 8
#define NFC_UID_CHANGE_CONFIRM_COUNT 3
#define HEARTBEAT_MIN_MS 5000
#define HEARTBEAT_JITTER_MS 3000
#define CHANNEL_DWELL_MS 420
#define LED_ACTIVE_HIGH 1
