#pragma once
#define NFC_SCAN_INTERVAL_MS 40
#define PRESENT_CONFIRM_COUNT 1
#define REMOVE_GRACE_MS 220
#define HEARTBEAT_MIN_MS 200
#define HEARTBEAT_JITTER_MS 0
#define CHANNEL_DWELL_MS 2500
#define LED_ACTIVE_HIGH 1
